plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.binxgtl.messengervamos'
    compileSdk 37

    defaultConfig {
        applicationId 'io.github.binxgtl.messengervamos'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '0.4.0-m4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'io.github.libxposed:service:102.0.0'
}
